[build]
  command = "npm run build"
  publish = "dist"

# Change the version of Hugo you want to use on Netlify
# by changing this environment variable.
[build.environment]
  HUGO_VERSION = "0.21"

[context.deploy-preview]
  command = "npm run build-preview"
